# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# https://docs.gradle.org/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# org.gradle.parallel=true

# Use AndroidX instead of the legacy Android Support Library.
android.useAndroidX=true
# Only generate R classes for each module's own resources.
android.nonTransitiveRClass=true
